name: build

on:
  push:
    branches:
      - "main"

env:
  # Build env variables
  REGISTRY_HOST: hub.yottab.io
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: "Set IMG_NAME variable"
        run: echo 'IMG_NAME=${{ env.REGISTRY_HOST }}/rubick/kloud-dns' >>$GITHUB_ENV

      - name: "Set IMG_TAG variable"
        run: echo 'IMG_TAG=${{ env.BRANCH_NAME }}' >>$GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login to ${{ env.REGISTRY_HOST }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          file: Dockerfile
          push: true
          tags: ${{ env.IMG_NAME }}:${{ env.IMG_TAG }}
